[package]
name = "trident"
version = "0.1.1"
edition = "2021"
authors = [ "Robin Schroer" ]
description = "Runs programs in parallel"
license = "MIT"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4", features = ["derive"] }
