[package]
name = "trident"
version = "0.1.0"
edition = "2021"
authors = [ "Robin Schroer" ]
description = "Runs programs in parallel"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["process", "full"] }
