version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.74
    steps:
      - checkout
      - run: |
          cargo install cargo-junit
          cargo junit --name output.xml
      - store_test_results:
          path: output.xml

workflows:
  build:
    jobs:
      - build
